export const ADD_WRITE = 'WEB_BLUETOOTH_DFU_ADD_WRITE'
export const UPDATE_WRITE = 'WEB_BLUETOOTH_DFU_UPDATE_WRITE'
export const REMOVE_WRITE = 'WEB_BLUETOOTH_DFU_REMOVE_WRITE'
//
export const ADD_TRANSFER_OBJECT = 'WEB_BLUETOOTH_DFU_ADD_TRANSFER_OBJECT'
export const UPDATE_TRANSFER_OBJECT = 'WEB_BLUETOOTH_DFU_UPDATE_TRANSFER_OBJECT'
export const REMOVE_TRANSFER_OBJECT = 'WEB_BLUETOOTH_DFU_REMOVE_TRANSFER_OBJECT'
//
export const ADD_TRANSFER = 'WEB_BLUETOOTH_DFU_ADD_TRANSFER'
export const UPDATE_TRANSFER = 'WEB_BLUETOOTH_DFU_UPDATE_TRANSFER'
export const REMOVE_TRANSFER = 'WEB_BLUETOOTH_DFU_REMOVE_TRANSFER'
//
export const ADD_UPDATE = 'WEB_BLUETOOTH_DFU_ADD_UPDATE'
export const MODIFY_UPDATE = 'WEB_BLUETOOTH_DFU_MODIFY_UPDATE'
export const REMOVE_UPDATE = 'WEB_BLUETOOTH_DFU_REMOVE_UPDATE'
