export const ADD_WRITE = 'WEB_BLUETOOTH_DFU_ADD_WRITE'
export const UPDATE_WRITE = 'WEB_BLUETOOTH_DFU_UPDATE_WRITE'
export const REMOVE_WRITE = 'WEB_BLUETOOTH_DFU_REMOVE_WRITE'
//
export const ADD_TRANSFER_OBJECT = 'WEB_BLUETOOTH_DFU_ADD_TRANSFER_OBJECT'
export const UPDATE_TRANSFER_OBJECT = 'WEB_BLUETOOTH_DFU_UPDATE_TRANSFER_OBJECT'
export const REMOVE_TRANSFER_OBJECT = 'WEB_BLUETOOTH_DFU_REMOVE_TRANSFER_OBJECT'
